/*
 * Weather Forecast API
 * This is the swagger definition of the weather forecast API. For more info contact sdimopoulos@irisweb.gr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sdimopoulos@irisweb.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherForecastApi) {
      root.WeatherForecastApi = {};
    }
    root.WeatherForecastApi.CityCoords = factory(root.WeatherForecastApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CityCoords model module.
   * @module model/CityCoords
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CityCoords</code>.
   * @alias module:model/CityCoords
   * @class
   * @param lat {Number} 
   * @param lon {Number} 
   */
  var exports = function(lat, lon) {
    this.lat = lat;
    this.lon = lon;
  };

  /**
   * Constructs a <code>CityCoords</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CityCoords} obj Optional instance to populate.
   * @return {module:model/CityCoords} The populated <code>CityCoords</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('lat'))
        obj.lat = ApiClient.convertToType(data['lat'], 'Number');
      if (data.hasOwnProperty('lon'))
        obj.lon = ApiClient.convertToType(data['lon'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} lat
   */
  exports.prototype.lat = undefined;

  /**
   * @member {Number} lon
   */
  exports.prototype.lon = undefined;

  return exports;

}));
