/*
 * Weather Forecast API
 * This is the swagger definition of the weather forecast API. For more info contact sdimopoulos@irisweb.gr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sdimopoulos@irisweb.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeatherForecastApi);
  }
}(this, function(expect, WeatherForecastApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('City', function() {
      beforeEach(function() {
        instance = new WeatherForecastApi.City();
      });

      it('should create an instance of City', function() {
        // TODO: update the code to test City
        expect(instance).to.be.a(WeatherForecastApi.City);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property coords (base name: "coords")', function() {
        // TODO: update the code to test the property coords
        expect(instance).to.have.property('coords');
        // expect(instance.coords).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property currWeatherIconId (base name: "currWeatherIconId")', function() {
        // TODO: update the code to test the property currWeatherIconId
        expect(instance).to.have.property('currWeatherIconId');
        // expect(instance.currWeatherIconId).to.be(expectedValueLiteral);
      });

      it('should have the property forecastInfo (base name: "forecastInfo")', function() {
        // TODO: update the code to test the property forecastInfo
        expect(instance).to.have.property('forecastInfo');
        // expect(instance.forecastInfo).to.be(expectedValueLiteral);
      });

    });
  });

}));
